In [1]:
import numpy as np

In [18]:
d = np.array ([10,46,20,2,1,24,8,88,22,5])
e = np.array ([4,6,7,9,11,12,55,59,56,69])

In [19]:
print(len(d))
print(len(e))

10
10


In [20]:
#math oparations

In [21]:
#adding 

In [23]:
print(d+e)
print (np.add(d,e))

[ 14  52  27  11  12  36  63 147  78  74]
[ 14  52  27  11  12  36  63 147  78  74]


In [24]:
#sub

In [26]:
print(d - e)
print (np.subtract(d,e))

[  6  40  13  -7 -10  12 -47  29 -34 -64]
[  6  40  13  -7 -10  12 -47  29 -34 -64]


In [27]:
# multipilication 

In [28]:
print (d*e)
print (np.multiply(d,e))

[  40  276  140   18   11  288  440 5192 1232  345]
[  40  276  140   18   11  288  440 5192 1232  345]


In [29]:
# division 

In [30]:
print (d/e)
print (np.divide(d,e))

[2.5        7.66666667 2.85714286 0.22222222 0.09090909 2.
 0.14545455 1.49152542 0.39285714 0.07246377]
[2.5        7.66666667 2.85714286 0.22222222 0.09090909 2.
 0.14545455 1.49152542 0.39285714 0.07246377]


In [31]:
#sqrt using for loop
g = np.array ([66,85,22,9,49])

In [32]:
import math
sqrt = math.sqrt

In [34]:
g = np.array ([66])
for h in g:
    print(sqrt(g))

8.12403840463596


In [36]:
g = np.array ([85])
for h in g:
    print(sqrt(g))

9.219544457292887


In [37]:
g = np.array ([22])
for h in g:
    print(sqrt(g))

4.69041575982343


In [38]:
g = np.array ([9])
for h in g:
    print(sqrt(g))

3.0


In [39]:
g = np.array ([49])
for h in g:
    print(sqrt(g))

7.0


In [40]:
#creating array and using postive and negative (slicing&index)

In [41]:
w = np.array ([5,3,22,16,65,4,80,33,21,12,34,48,90,93,77])

In [43]:
#positive index

print(w[3])

16


In [45]:
print (w[8:12])

[21 12 34 48]


In [47]:
print (w[0:])

[ 5  3 22 16 65  4 80 33 21 12 34 48 90 93 77]


In [48]:
print (w[:15])

[ 5  3 22 16 65  4 80 33 21 12 34 48 90 93 77]


In [49]:
#negitive index

print (w[-13:-5])

[22 16 65  4 80 33 21 12]


In [50]:
print (w[-7])

21


In [51]:
print (w[-10:])

[ 4 80 33 21 12 34 48 90 93 77]


In [52]:
print (w[:-3])

[ 5  3 22 16 65  4 80 33 21 12 34 48]


In [53]:
a = np.array([[67,57,19,28,32,63],[55,54,39,44,76,23]])

In [55]:
print (a[0,1:7])

[57 19 28 32 63]


In [57]:
print (a[1,-7:-3])

[55 54 39]
